# permissions for end users to view pvcsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvcsnapshot-viewer-role
rules:
- apiGroups:
  - frq.akfarooqnaveen.com
  resources:
  - pvcsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frq.akfarooqnaveen.com
  resources:
  - pvcsnapshots/status
  verbs:
  - get
